name: Diabetes_Project_CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Diabetes Risk Analysis_PySpark/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Diabetes Risk Analysis_PySpark/**'

jobs:
  check:
    name: Syntax and Path Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Python Syntax Check
        run: |
          python -m py_compile "Diabetes Risk Analysis_PySpark/Diabetes_Analysis_Medallion_PySpark.py"