name: Diabetes_Project_CI

on:
  push:
    # 어떤 브랜치에 push해도 작동하도록 설정 (테스트용)
    branches: ["*"] 
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Python Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Syntax Check
        # 폴더 경로를 명시하지 않고 전체에서 .py 파일을 찾도록 수정
        run: |
          find . -name "*.py" -exec python -m py_compile {} +
